In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[0]

np.int64(1)

In [4]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [5]:
a[:3]

array([10,  2,  3])

In [6]:
b = a[3:]
b

array([4, 5, 6])

In [7]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
a[1, 3]

np.int64(8)

0-D (zero-dimensional) array = Scalar

1-D (one-dimensional) array = Vector

2-D (two-dimensional) array = Matrix

N-D (N-dimensional) array = Tensor

In [11]:
a.ndim

2

In [12]:
a.shape

(4, 4)

In [14]:
len(a.shape) == a.ndim

True

In [13]:
a.size

16

In [15]:
import math
a.size == math.prod(a.shape)

True

In [16]:
a.dtype

dtype('int64')

In [17]:
np.zeros(2)

array([0., 0.])

In [18]:
np.ones(2)

array([1., 1.])

In [19]:
np.empty(2)

array([1., 1.])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(2, 13, 3)

array([ 2,  5,  8, 11])

In [22]:
np.linspace(0, 20, num=5)

array([ 0.,  5., 10., 15., 20.])

In [23]:
np.ones(4, dtype=np.int64)

array([1, 1, 1, 1])

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
y = np.array([[9, 10, 11, 12]])
np.concatenate((x, y), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                           
                           [[8, 9, 10, 11],
                            [12, 13, 14, 15]],
                            
                            [[16, 17, 18, 19],
                             [20, 21, 22, 23]]])

array_example

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
array_example.ndim

3

In [31]:
array_example.size

24

In [32]:
array_example.shape

(3, 2, 4)

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [34]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [38]:
print(row_vector)

[[1 2 3 4 5 6]]


In [39]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])

[1 2 3 4]


In [40]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [44]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [45]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [46]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [47]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [48]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [53]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)

[2 3]
[0 1]
[1 2]
[1. 2.]


In [54]:
a = np.arange(6)
print(a)
a.sum()

[0 1 2 3 4 5]


np.int64(15)

In [56]:
a = np.array([[1, 1],
              [2, 2]])
a.sum(axis=1)

array([2, 4])

In [63]:
a = np.array([1, 2, 7, 4, 10])
a.sum()


np.int64(24)

In [64]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
np.empty(3)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(a, axis=1)
print(reversed_arr)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
a1 = a.flatten()
print(a1)
a1[0] = 99
print(a1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
a2 = x.ravel()
print(a2)
a2[0] = 99
print(a2)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[99  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [72]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('array', a)

In [74]:
b = np.load('array.npy')
print(b)

[1 2 3 4 5 6]


In [76]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)

In [77]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [78]:
import pandas as pd

In [79]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928
